engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    exclude_paths:
      - "test/"
    config:
      languages:
      - javascript:
ratings:
  paths:
  - src/**
  - test/**
exclude_paths:
- "docs/"
- "dist/"
